DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "blogs" CASCADE;
DROP TABLE IF EXISTS "posts" CASCADE;
DROP TABLE IF EXISTS "tags" CASCADE;
DROP TABLE IF EXISTS "posts_tags" CASCADE;
DROP TABLE IF EXISTS "comments" CASCADE;
DROP TABLE IF EXISTS "comments_closure" CASCADE;
DROP TABLE IF EXISTS "likes" CASCADE;